version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: obrigacoes
      POSTGRES_USER: obrigacoes
      POSTGRES_PASSWORD: obrigacoes
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://obrigacoes:obrigacoes@db:5432/obrigacoes
      DEBUG: "True"
      ALLOWED_HOSTS: "*"
    ports:
      - "8000:8000"
  web:
    build: ./frontend
    depends_on:
      - api
    environment:
      VITE_API_URL: http://localhost:8000/api
    ports:
      - "5173:5173"
volumes:
  pgdata:
