# Generated by Django 5.0.6 on 2025-09-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Endereço"),
        ),
        migrations.AddField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Criado em"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="fantasy_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Nome Fantasia"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefone"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="responsible",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Responsável"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Atualizado em"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AlterField(
            model_name="company",
            name="cnpj",
            field=models.CharField(
                blank=True, max_length=18, null=True, verbose_name="CNPJ"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Razão Social"),
        ),
    ]
