# Generated by Django 5.0.6 on 2025-09-24 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_company_options_company_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="obligationtype",
            name="periodicity",
        ),
        migrations.AddField(
            model_name="obligation",
            name="responsible_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responsible_obligations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário Responsável",
            ),
        ),
        migrations.AddField(
            model_name="obligation",
            name="validity_end_date",
            field=models.DateField(
                default="2024-12-31",
                help_text="Data de fim do controle desta obrigação",
                verbose_name="Data Final de Validade",
            ),
        ),
        migrations.AddField(
            model_name="obligation",
            name="validity_start_date",
            field=models.DateField(
                default="2024-01-01",
                help_text="Data de início do controle desta obrigação",
                verbose_name="Data Inicial de Validade",
            ),
        ),
        migrations.AddField(
            model_name="obligationtype",
            name="due_day",
            field=models.IntegerField(
                default=1,
                help_text="Dia do mês para vencimento (1-31)",
                verbose_name="Dia de Vencimento",
            ),
        ),
        migrations.AddField(
            model_name="obligationtype",
            name="recurrence",
            field=models.CharField(
                choices=[
                    ("mensal", "Mensal"),
                    ("bimestral", "Bimestral"),
                    ("trimestral", "Trimestral"),
                    ("semestral", "Semestral"),
                    ("anual", "Anual"),
                    ("especifico", "Data Específica"),
                ],
                default="mensal",
                max_length=20,
                verbose_name="Recorrência",
            ),
        ),
        migrations.AlterField(
            model_name="obligation",
            name="delivery_deadline",
            field=models.DateField(
                blank=True, null=True, verbose_name="Prazo de Entrega"
            ),
        ),
        migrations.AlterField(
            model_name="obligation",
            name="due_date",
            field=models.DateField(verbose_name="Data de Vencimento"),
        ),
    ]
