# Generated by Django 5.0.6 on 2025-09-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obligation",
            name="validity_end_date",
            field=models.DateField(
                blank=True,
                help_text="Data de fim do controle desta obrigação",
                null=True,
                verbose_name="Data Final de Validade",
            ),
        ),
        migrations.AlterField(
            model_name="obligation",
            name="validity_start_date",
            field=models.DateField(
                blank=True,
                help_text="Data de início do controle desta obrigação",
                null=True,
                verbose_name="Data Inicial de Validade",
            ),
        ),
    ]
