# Generated by Django 5.0.6 on 2025-09-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_obligation_validity_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="obligation",
            name="obligation_name",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Nome da Obrigação Acessória",
            ),
        ),
    ]
