# Generated by Django 5.0.6 on 2025-09-26 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_obligation_obligation_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="batch_id",
            field=models.UUIDField(
                blank=True,
                help_text="Para rastrear entregas em massa",
                null=True,
                verbose_name="ID do Lote",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="submission_type",
            field=models.CharField(
                choices=[("original", "Original"), ("retificadora", "Retificadora")],
                default="original",
                max_length=20,
                verbose_name="Tipo de Entrega",
            ),
        ),
        migrations.CreateModel(
            name="SubmissionAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="attachments/%Y/%m/%d/")),
                ("original_filename", models.CharField(max_length=255)),
                ("parsed_cnpj", models.CharField(blank=True, max_length=14, null=True)),
                (
                    "parsed_period",
                    models.CharField(
                        blank=True, help_text="MMAAAA", max_length=6, null=True
                    ),
                ),
                (
                    "parsed_obligation_key",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="core.submission",
                    ),
                ),
            ],
        ),
    ]
