# Generated by Django 5.0.6 on 2025-10-15 22:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_submission_approval"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("due_soon", "Vencimento Próximo"),
                    ("overdue", "Atrasado"),
                    ("reminder", "Lembrete"),
                    ("system", "Sistema"),
                    ("approval", "Aprovação"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Dispatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("NOTIFICACAO_FISCAL", "Notificação Fiscal"),
                            ("FISCALIZACAO", "Fiscalização"),
                            ("DESPACHO_DECISORIO", "Despacho Decisório"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Título"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Data Inicial")),
                ("end_date", models.DateField(verbose_name="Data Final")),
                (
                    "progress_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Progresso (%)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NAO_INICIADO", "Não Iniciado"),
                            ("EM_ANDAMENTO", "Em Andamento"),
                            ("CONCLUIDO", "Concluído"),
                        ],
                        default="NAO_INICIADO",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatches",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_dispatches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_dispatches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Despacho",
                "verbose_name_plural": "Despachos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DispatchSubtask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nome da Subatividade"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NAO_INICIADO", "Não Iniciado"),
                            ("EM_ANDAMENTO", "Em Andamento"),
                            ("CONCLUIDO", "Concluído"),
                        ],
                        default="NAO_INICIADO",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Ordem")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_subtasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispatch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="core.dispatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subatividade",
                "verbose_name_plural": "Subatividades",
                "ordering": ["order", "created_at"],
                "unique_together": {("dispatch", "order")},
            },
        ),
    ]
